spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service

  profiles:
    active: dev # Utiliser l'environnement "application-dev.yml" par défaut.